using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Linq;

namespace TeraDataExtractor
{
    /// <summary>
    /// Extracts dungeon names - maybe they're already contained in the file generated by RegionExtractor?
    /// Structure: id, name
    /// </summary>
    public class DungeonsExtractor
    {
        private string RootFolder = Program.SourcePath;
        private string OutFolder = Path.Combine(Program.OutputPath, "dungeons");

        public DungeonsExtractor(string region)
        {
            Directory.CreateDirectory(OutFolder);
            var lines = new List<string>();
            XDocument.Load(Path.Combine(RootFolder, region, "StrSheet_Dungeon", "StrSheet_Dungeon-0.xml")).
            Descendants().Where(x => x.Name == "String").ToList().ForEach(s =>
            {
                var id = s.Attribute("id").Value;
                var name = s.Attribute("string").Value;
                lines.Add(id + "\t" + name);
            });
            File.WriteAllLines(Path.Combine(OutFolder, $"dungeons-{region}.tsv"), lines);

        }
    }
}
